FROM python:3.6-alpine

ENV PYTHONUNBUFFERED 1

RUN apk update \
  # Convenience
  && apk add bash postgresql-client \
  # psycopg2 dependencies
  && apk add --virtual build-deps gcc python3-dev musl-dev \
  && apk add postgresql-dev \
  # Pillow dependencies
  && apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev \
  # CFFI dependencies
  && apk add libffi-dev py-cffi

RUN addgroup -S django \
    && adduser -S -G django django

RUN mkdir /app

WORKDIR /app

ENTRYPOINT ["/app/bin/entrypoint-dev"]
